# Tap necessary repositories
tap "homebrew/core"

# Install command-line utilities
brew "bat"
brew "bottom"
brew "thefuck"
brew "duf"
brew "fastfetch"
brew "tmux"
brew "lsd"
brew "ripgrep"
brew "tree"
brew "htop"
brew "pandoc"
brew "neovim"
