tap "homebrew/bundle"
tap "mas-cli/mas"
tap "nikitabobko/tap"
brew "ansible"
brew "ansible-lint"
brew "bat"
brew "btop"
brew "draft"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "lsd"
brew "mas"
brew "micro"
brew "neovim"
brew "poppler"
brew "ripgrep"
brew "sevenzip"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "aerospace"
cask "alfred"
cask "appcleaner"
cask "devpod"
cask "discord"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "heynote"
cask "istat-menus"
cask "iterm2"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "maccy"
cask "megasync"
cask "obsidian"
cask "rectangle-pro"
cask "shottr"
cask "signal"
cask "spotify"
cask "sublime-text"
cask "textsniper"
cask "visual-studio-code"
cask "vivaldi"
cask "wezterm"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "Drafts", id: 1435957248
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "InstaRemind", id: 1492317385
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Obsidian Web Clipper", id: 6720708363
mas "Pages", id: 409201541
mas "PDFgear", id: 6469021132
mas "Pure Paste", id: 1611378436
mas "Things", id: 904280696
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.project-manager"
vscode "andenetalexander.vim-cheatsheet"
vscode "catppuccin.catppuccin-vsc"
vscode "davidanson.vscode-markdownlint"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "github.github-vscode-theme"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "pkief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "zhuangtongfa.material-theme"
