tap "hashicorp/tap"
tap "homebrew/bundle"
tap "mas-cli/mas"
tap "nikitabobko/tap"
brew "tree"
brew "ansible"
brew "ansible-lint"
brew "awscli"
brew "bat"
brew "btop"
brew "draft"
brew "duf"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "glow"
brew "gum"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "lima"
brew "lsd"
brew "mas"
brew "micro"
brew "neovim"
brew "nmap"
brew "poppler"
brew "ripgrep"
brew "sevenzip"
brew "sshpass"
brew "starship"
brew "stow"
brew "syncthing"
brew "tmux"
brew "whois"
brew "yamllint"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "hashicorp/tap/terraform"
cask "1password"
cask "aerospace"
cask "alfred"
cask "appcleaner"
cask "coteditor"
cask "discord"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "heynote"
cask "istat-menus"
cask "iterm2"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "kitty"
cask "maccy"
cask "megasync"
cask "microsoft-edge"
cask "obsidian"
cask "octarine"
cask "proton-drive"
cask "raspberry-pi-imager"
cask "rectangle-pro"
cask "shottr"
cask "signal"
cask "spotify"
cask "standard-notes"
cask "sublime-text"
cask "textsniper"
cask "visual-studio-code"
cask "vivaldi"
cask "wezterm"
cask "windows-app"
cask "zed"
cask "zen"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "iMovie", id: 408981434
mas "InstaRemind", id: 1492317385
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Obsidian Web Clipper", id: 6720708363
mas "Pages", id: 409201541
mas "Pure Paste", id: 1611378436
mas "Things", id: 904280696
vscode "aaron-bond.better-comments"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.path-intellisense"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "hashicorp.terraform"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "timonwong.shellcheck"
vscode "usernamehw.errorlens"
vscode "vscode-icons-team.vscode-icons"
vscode "wayou.vscode-todo-highlight"
vscode "yzhang.markdown-all-in-one"
