# Alacritty configuration file

# Import theme configurations (uncomment the theme you want to use)
import = [
  #    "~/dotfiles/.config/alacritty/themes/ayu_mirage.toml"
  #    "~/dotfiles/.config/alacritty/themes/baitong.toml"
  #    "~/dotfiles/.config/alacritty/themes/catppuccin_mocha.toml"
  #    "~/dotfiles/.config/alacritty/themes/dracula.toml"
  #    "~/dotfiles/.config/alacritty/themes/everforest_dark.toml"
  #    "~/dotfiles/.config/alacritty/themes/gruvbox_dark.toml"
  #    "~/dotfiles/.config/alacritty/themes/horizon_dark.toml"
  #    "~/dotfiles/.config/alacritty/themes/papercolor_dark.toml"
  #    "~/dotfiles/.config/alacritty/themes/rose_pine_moon.toml"
  #    "~/dotfiles/.config/alacritty/themes/tokyo_night.toml"
    "~/dotfiles/.config/alacritty/themes/thelovelace.toml"
]

# Shell settings
[shell]
program = "/bin/zsh"
args = ["-l"]

# Window settings
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }


# Font settings
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 13.0
