#~/.config/starship.toml

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
